---
jobs:
  push:
    if: "github.event_name == 'push' && contains(toJson(github.event.commits), 'NO_CI') == false"
    runs-on: ubuntu-latest
    steps:
      -
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          token: "${{ secrets.GITHUB_TOKEN}}"
      -
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      -
        env:
          FIREBASE_CONFIG: "${{secrets.GOOGLE_SERVICES_JSON}}"
        id: setup
        run: |
          echo $FIREBASE_CONFIG | base64 --decode --ignore-garbage > app/google-services.json
          echo '${{ secrets.SERVICE_ACCOUNT_JSON }}' > service_account.json
          echo "::set-output name=LATEST_TAG::$(git describe --tags `git rev-list --tags --max-count=1`)"
          echo "::set-output name=COMMIT_NUM::$(git rev-list --count master)"
      -
        uses: chkfung/android-version-actions@v1.1
        with:
          gradlePath: app/build.gradle
          versionCode: "${{steps.setup.outputs.COMMIT_NUM}}"
          versionName: "${{steps.setup.outputs.LATEST_TAG}}"
      -
        run: |
          chmod +x build.gradle
          ./gradlew build
          ./gradlew bundleRelease
      -
        uses: r0adkll/sign-android-release@v1
        with:
          alias: "${{secrets.RELEASE_KEY_ALIAS}}"
          keyPassword: "${{secrets.RELEASE_KEY_PASSWORD}}"
          keyStorePassword: "${{secrets.RELEASE_KEYSTORE_PASSWORD}}"
          releaseDirectory: app/build/outputs/bundle/release
          signingKeyBase64: "${{secrets.SIGNING_KEY}}"
      -
        uses: actions/upload-artifact@v1
        with:
          name: WearOS
          path: app/build/outputs/bundle/release/app-prod-release.aab
      -
        uses: r0adkll/upload-google-play@v1
        with:
          packageName: digital.lamp.mindlamp
          releaseFile: app/build/outputs/bundle/release/app-prod-release.aab
          serviceAccountJson: service_account.json
          status: completed
          track: beta
name: Publish
true:
  push:
    branches:
      - master
  release:
    types:
      - created
