/**
* LAMP Platform
* The LAMP Platform API.
*
* The version of the OpenAPI document: 1.0.0
* Contact: team@digitalpsych.org
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package digital.lamp.models

import com.squareup.moshi.Json
import android.os.Parcelable
import kotlinx.android.parcel.Parcelize
import kotlinx.android.parcel.RawValue

import java.io.Serializable
/**
 * An activity that may be performed by a participant in a study.
 * @param id A globally unique reference for objects.
 * @param spec A globally unique reference for objects.
 * @param name The name of the activity.
 * @param schedule 
 * @param settings The configuration settings for the activity.
 */
@Parcelize

data class Activity (
    /* A globally unique reference for objects. */
    @Json(name = "id")
    var id: kotlin.String? = null,
    /* A globally unique reference for objects. */
    @Json(name = "spec")
    var spec: kotlin.String? = null,
    /* The name of the activity. */
    @Json(name = "name")
    var name: kotlin.String? = null,
    @Json(name = "schedule")
    var schedule: DurationIntervalLegacy? = null,
    /* The configuration settings for the activity. */
    @Json(name = "settings")
    var settings: @RawValue kotlin.Any? = null
) : Serializable, Parcelable {
	companion object {
		private const val serialVersionUID: Long = 123
	}

}

