/**
* LAMP Platform
* The LAMP Platform API.
*
* The version of the OpenAPI document: 1.0.0
* Contact: team@digitalpsych.org
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package digital.lamp.models

import android.os.Parcelable
import com.squareup.moshi.Json
import kotlinx.android.parcel.Parcelize
import kotlinx.android.parcel.RawValue
import java.io.Serializable


/**
 * An event generated by the participant interacting with an `Activity`.
 * @param timestamp 
 * @param duration The duration this event lasted before recording ended.
 * @param activity A globally unique reference for objects.
 * @param data The summary information for the activity event as determined by the activity that created this activity event.
 * @param temporalSlices The specific interaction details of the activity event.
 */
@Parcelize

data class ActivityEvent (
    @Json(name = "timestamp")
    var timestamp: java.sql.Timestamp? = null,
    /* The duration this event lasted before recording ended. */
    @Json(name = "duration")
    var duration: kotlin.Long? = null,
    /* A globally unique reference for objects. */
    @Json(name = "activity")
    var activity: kotlin.String? = null,
    /* The summary information for the activity event as determined by the activity that created this activity event. */
    @Json(name = "data")
    var data: @RawValue kotlin.Any? = null,
    /* The specific interaction details of the activity event. */
//    @Json(name = "temporal_slices")
//    var temporalSlices: @RawValue kotlin.Array<kotlin.Any>? = null
) : Serializable, Parcelable {
	companion object {
		private const val serialVersionUID: Long = 123
	}

}

