/**
* LAMP Platform
* The LAMP Platform API.
*
* The version of the OpenAPI document: 1.0.0
* Contact: team@digitalpsych.org
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package digital.lamp.models



import com.squareup.moshi.Json
import android.os.Parcelable
import kotlinx.android.parcel.Parcelize
import kotlinx.android.parcel.RawValue

import java.io.Serializable
/**
 * 
 * @param repeatType 
 * @param date 
 * @param customTimes 
 */
@Parcelize

data class DurationIntervalLegacy (
    @Json(name = "repeat_type")
    var repeatType: kotlin.String? = null,
    @Json(name = "date")
    var date: java.sql.Timestamp? = null,
    @Json(name = "custom_times")
    var customTimes: @RawValue kotlin.Array<kotlin.Any>? = null
) : Serializable, Parcelable {
	companion object {
		private const val serialVersionUID: Long = 123
	}

}

