/**
* LAMP Platform
* The LAMP Platform API.
*
* The version of the OpenAPI document: 1.0.0
* Contact: team@digitalpsych.org
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package digital.lamp.models

import com.squareup.moshi.Json
import android.os.Parcelable
import kotlinx.android.parcel.Parcelize
import kotlinx.android.parcel.RawValue

import java.io.Serializable
/**
 * An event generated by a participant interacting with the LAMP app.
 * @param timestamp 
 * @param sensor The type of the sensor event.
 * @param data The item information recorded within the sensor event.
 */
@Parcelize
data class SensorEvent (
        @Json(name = "data")
        var data: @RawValue Any,
        @Json(name = "sensor")
        var sensor: String,
        /* The item information recorded within the sensor event. */
        @Json(name = "timestamp")
        var timestamp: Double
        /* The type of the sensor event. */
) : Serializable, Parcelable {
	companion object {
		private const val serialVersionUID: Long = 123
	}

}

