/**
* LAMP Platform
* The LAMP Platform API.
*
* The version of the OpenAPI document: 1.0.0
* Contact: team@digitalpsych.org
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package digital.lamp.models

import com.squareup.moshi.Json
import android.os.Parcelable
import kotlinx.android.parcel.Parcelize

import java.io.Serializable
/**
 * 
 * @param id A globally unique reference for objects.
 * @param name The name of the study.
 * @param activities The set of all activities available in the study.
 * @param participants The set of all enrolled participants in the study.
 */
@Parcelize

data class Study (
    /* A globally unique reference for objects. */
    @Json(name = "id")
    var id: kotlin.String? = null,
    /* The name of the study. */
    @Json(name = "name")
    var name: kotlin.String? = null,
    /* The set of all activities available in the study. */
//    @Json(name = "activities")
//    var activities: Array<Any>? = null,
//    /* The set of all enrolled participants in the study. */
//    @Json(name = "participants")
//    var participants: Array<Any>? = null
) : Serializable, Parcelable {
	companion object {
		private const val serialVersionUID: Long = 123
	}

}

