name: Android CI

on:
  push:
    branches: [ master ]

jobs:
   apk:
    name: Deploy APK
    runs-on: ubuntu-18.04

    steps:
      - uses: actions/checkout@v1
      - name: set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Build debug APK
        run: bash ./gradlew assembleDebug --stacktrace
      - name: Signed Apk
        uses:  r0adkll/sign-android-release@v1
        with:
            releaseDirectory: app/build/outputs/apk/release
            signingKeyBase64: ${{ secrets.SIGNING_KEY }}
            alias: ${{ secrets.RELEASE_KEY_ALIAS }}
            keyStorePassword: ${{ secrets.RELEASE_KEYSTORE_PASSWORD }}
            keyPassword: ${{ secrets.RELEASE_KEY_PASSWORD }}
          
  
          
 
        
