name: Android CI

on:
  push:
    branches: [ master ]

jobs:
   apk:
    name: Deploy APK
    runs-on: ubuntu-18.04

    steps:
      - uses: actions/checkout@v1
      - name: set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Android Builder
        uses: b4s36t4/Android-Action@0.0.1

    
          
  
          
 
        
