name: Android CI

on:
  push:
    branches: [ master ]

jobs:
   apk:
    name: Deploy APK
    runs-on: ubuntu-18.04

    steps:
      
    - uses: actions/checkout@v1
    - name: set up JDK 1.8

      uses: actions/setup-java@v1

      with:

        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

        java-version: 1.8

    - name: "Permission to gradle File"

      run: chmod +x gradlew

    - name: Build with Gradle

      run: ./gradlew assemble

    - name: Commit files

      run: |

        echo ${{ github.ref }}

        git add .

        git config --local user.email "arunvijayan@microobejcts.net"

        git config --local user.name "arunvijayan"

        git commit -m "ci: Automated build push" -a | exit 0

    - name: Push changes

      if: github.ref == 'refs/heads/master'

      uses: ad-m/github-push-action@master

      with:

        github_token: ${{ secrets.GITHUB_TOKEN }}
