name: Deploy LampV2 CI

on:
  push:
    branches: [ master ]

jobs:
  build:
    
    runs-on: ubuntu-latest
    
    steps:
      
      - name: Checkout
        uses: actions/checkout@v2 
      
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8   
        
      - name: Bump version
        uses: chkfung/android-version-actions@v1.1
        with:
          gradlePath: app/build.gradle
          versionCode: ${{github.run_number}}
          
      - name: Generate build number
        uses: einaregilsson/build-number@v1 
        with: 
          token: ${{secrets.github_token}}        
     
      - name: Print generated build number for test
        run: echo Build number is $BUILD_NUMBER


    

 
