name: Publish
on:
  push:
    branches: [master]
  release:
    types: [created]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2 
        with:
          fetch-depth: 0
      - uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - id: setup
        run: |
          echo $FIREBASE_CONFIG | base64 --decode --ignore-garbage > app/google-services.json
          echo '${{ secrets.SERVICE_ACCOUNT_JSON }}' > service_account.json
          echo "::set-output name=LATEST_TAG::$(git describe --tags `git rev-list --tags --max-count=1`)"
          echo "::set-output name=COMMIT_NUM::$(git rev-list --count master)"
        env:
          FIREBASE_CONFIG: ${{secrets.GOOGLE_SERVICES_JSON}}
      - uses: chkfung/android-version-actions@v1.1
        with:
          gradlePath: app/build.gradle
          versionCode: ${{steps.setup.outputs.COMMIT_NUM}}
          versionName: ${{steps.setup.outputs.LATEST_TAG}}

      -run: |
          git commit -m "Version changes"

      - name: Push changes
      -uses: ad-m/github-push-action@master
              with:
                github_token: ${{ secrets.GITHUB_TOKEN }}
                branch: ${{ github.ref }}
      - run: |
          chmod +x build.gradle
          ./gradlew build
          ./gradlew bundleRelease
      - uses: r0adkll/sign-android-release@v1
        with:
          releaseDirectory: app/build/outputs/bundle/prodRelease
          signingKeyBase64: ${{secrets.SIGNING_KEY}}
          alias: ${{secrets.ALIAS}}
          keyStorePassword: ${{secrets.KEY_STORE_PASSWORD}}
          keyPassword: ${{secrets.KEY_PASSWORD}}
      - uses: actions/upload-artifact@v1
        with:
          name: mindLAMP
          path: app/build/outputs/bundle/prodRelease/app-prod-release.aab
      - uses: r0adkll/upload-google-play@v1
        with:
          serviceAccountJson: service_account.json
          packageName: digital.lamp.mindlamp
          releaseFile: app/build/outputs/bundle/prodRelease/app-prod-release.aab
          track: beta
          status: completed
