name: Publish
on:
  push:
    branches: [master]
  release:
    types: [created]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2 
        with:
          persist-credentials: false
          fetch-depth: 0
          token: ${{ secrets.PERSONAL_TOKEN }}
      - uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Do a commit for release type
        run: |
          git config --global user.name "$(git --no-pager log --format=format:'%an' -n 1)"
          git config --global user.email "$(git --no-pager log --format=format:'%ae' -n 1)
          git commit --allow-empty -m "empty commit"
          git push origin HEAD
