name: Publish
on:
  push:
    branches: [master]
  release:
    types: [created]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2 
        with:
          fetch-depth: 0
        env:
          token: ${{ secrets.PERSONAL_TOKEN }}
      - uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Do a commit for release type
        run: |
          git config --global user.email "saranya.sajeev@zcocorporation.com"
            git config --global user.name "saranya-sajeev"
          git commit --allow-empty -m "empty commit"
          git push origin HEAD
