name: wearos
on:
  push:
    branches: [master]
  release:
    types: [created]
jobs:
  wearosrelease:
    if: github.event_name == 'release' && contains(toJson(github.event.commits), 'NO_CI') == false
    runs-on: ubuntu-latest
    steps:
      -
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
        env:
          token: ${{ secrets.GITHUB_TOKENN }}
      -
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      -
        name: "Do a commit for release type"
        run: |
          echo "Version code before empty commit is $(git rev-list --count HEAD)"
          git config --global user.name "$(git --no-pager log --format=format:'%an' -n 1)"
          git config --global user.email "$(git --no-pager log --format=format:'%ae' -n 1)"
          git commit --allow-empty -m "NO_CI"
          git push origin HEAD:master
          echo "Version code after empty commit is $(git rev-list --count HEAD)"
      -
        env:
          FIREBASE_CONFIG: "${{secrets.GOOGLE_SERVICES_JSON}}"
        id: setup
        run: |
          echo $FIREBASE_CONFIG | base64 --decode --ignore-garbage > app/google-services.json
          echo '${{ secrets.SERVICE_ACCOUNT_JSON }}' > service_account.json
          echo "::set-output name=LATEST_TAG::$(git describe --tags `git rev-list --tags --max-count=1`)"
          echo "::set-output name=COMMIT_NUM::$(git rev-list --count HEAD)"
          echo "Version code before upload ${{steps.setup.outputs.COMMIT_NUM}}"

      -
        uses: chkfung/android-version-actions@v1.1
        with:
          gradlePath: app/build.gradle
          versionCode: "${{steps.setup.outputs.COMMIT_NUM}}"
          versionName: "${{steps.setup.outputs.LATEST_TAG}}"
      -
        run: |
          chmod +x build.gradle
          ./gradlew build
          ./gradlew bundleRelease
      -
        uses: r0adkll/sign-android-release@v1
        with:
          alias: "${{secrets.ALIAS}}"
          keyPassword: "${{secrets.KEY_PASSWORD}}"
          keyStorePassword: "${{secrets.KEY_STORE_PASSWORD}}"
          releaseDirectory: app/build/outputs/bundle/prodRelease
          signingKeyBase64: "${{secrets.SIGNING_KEY}}"
      -
        uses: actions/upload-artifact@v1
        with:
          name: mindLAMP
          path: app/build/outputs/bundle/prodRelease/app-prod-release.aab

      -
        uses: r0adkll/upload-google-play@v1
        with:
          serviceAccountJson: service_account.json
          packageName: digital.lamp.mindlamp
          releaseFile: app/build/outputs/bundle/prodRelease/app-prod-release.aab
          track: beta
          status: completed
  wearospush:
    if: github.event_name == 'push' && contains(toJson(github.event.commits), 'WEAR_OS_WORKFLOW') == true
    runs-on: ubuntu-latest
    steps:
      -
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
        env:
            token: ${{ secrets.GITHUB_TOKENN }}
      -
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      -
        env:
          FIREBASE_CONFIG: "${{secrets.GOOGLE_SERVICES_JSON}}"
          SIGNED_RELEASE_FILES: WearOs/app/build/outputs/bundle/prodRelease
        id: setup
        run: |
          echo $FIREBASE_CONFIG | base64 --decode --ignore-garbage > app/google-services.json
          echo '${{ secrets.SERVICE_ACCOUNT_JSON }}' > service_account.json
          echo "::set-output name=LATEST_TAG::$(git describe --tags `git rev-list --tags --max-count=1`)"
          echo "::set-output name=COMMIT_NUM::$(git rev-list --count master)"
      -
        uses: chkfung/android-version-actions@v1.1
        with:
          gradlePath: app/build.gradle
          versionCode: "${{steps.setup.outputs.COMMIT_NUM}}"
          versionName: "${{steps.setup.outputs.LATEST_TAG}}"

      - name: Make gradlew executable
        run: chmod +x ./gradlew
      -
        run: |
          cd WearOs
          chmod +x build.gradle
          chmod +x gradlew
          ./gradlew clean
          ./gradlew build
          ./gradlew bundleRelease
      -
        uses: r0adkll/sign-android-release@v1
        with:
          alias: "${{secrets.RELEASE_KEY_ALIAS}}"
          keyPassword: "${{secrets.RELEASE_KEY_PASSWORD}}"
          keyStorePassword: "${{secrets.RELEASE_KEY_PASSWORD}}"
          releaseDirectory: WearOs/app/build/outputs/bundle/qaRelease
          signingKeyBase64: "${{secrets.WEAR_OS_SIGNING_KEY}}"


      - uses: actions/upload-artifact@v1
        with:
          name: mindLAMP
          path: WearOs/app/build/outputs/bundle/qaRelease/app-qa-release.aab
      - uses: r0adkll/upload-google-play@v1
        with:
          serviceAccountJson: service_account.json
          packageName: digital.lamp.mindlamp
          releaseFile: WearOs/app/build/outputs/bundle/qaRelease/app-qa-release.aab
          track: beta
          status: completed

